src/main/java/com/adailsilva/model/Acesso.java
package com.adailsilva.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "acesso")
public class Acesso implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Getter
	@Setter
	@Column(nullable = false, length = 20)
	private String descricao;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Acesso other = (Acesso) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/adailsilva/model/BonusCliente.java
package com.adailsilva.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "bonus_cliente")
public class BonusCliente implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Getter
	@Setter
	@ManyToOne
	@JoinColumn(name = "id_cliente")
	private Cliente cliente;

	@Getter
	@Setter
	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date dataCriacao;

	@Getter
	@Setter
	@Column(nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date dataUso;
}

src/main/java/com/adailsilva/model/Cartao.java
package com.adailsilva.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "cartao")
public class Cartao implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Getter
	@Setter
	private String bandeira;

}

src/main/java/com/adailsilva/model/Categoria.java
package com.adailsilva.model;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotBlank;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "categoria")
public class Categoria implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Getter
	@Setter
	@Column(nullable = false, length = 20)
	@NotBlank(message = ": Descrição precisa ser preenchida !")
	private String descricao;

	@Getter
	@Setter
	@Column(nullable = false, length = 20)
	private String tipo;

	@Getter
	@Setter
	@OneToMany
	private List<Produto> produtos;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Categoria other = (Categoria) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/adailsilva/model/Cliente.java
package com.adailsilva.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.OneToMany;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name="cliente")
@PrimaryKeyJoinColumn(name = "idPessoa")
public class Cliente extends Pessoa implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@OneToMany(mappedBy = "cliente")
	private List<BonusCliente> bonus = new ArrayList<>();

	@Getter
	@Setter
	private Integer qtdPontos;

	@Getter
	@Setter
	@Transient
	private String dataString;

	@Getter
	@Setter
	@Column(nullable = false)
	private Date dataCriacao;

}

src/main/java/com/adailsilva/model/Endereco.java
package com.adailsilva.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotBlank;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "endereco")
public class Endereco implements Serializable {

	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Getter
	@Setter
	@Column(nullable = false, length = 20)
	@NotBlank(message = "Descrição : precisa ser preenchido.")
	private String descricao;

	@Getter
	@Setter
	@Column(nullable = false)
	@NotBlank(message = "Rua : precisa ser preenchido.")
	private String rua;

	@Getter
	@Setter
	@Column(nullable = false)
	@NotBlank(message = "Bairro : precisa ser preenchido.")
	private String bairro;

	@Getter
	@Setter
	@Column(nullable = false)
	@NotBlank(message = "Número : precisa ser preenchido.")
	private String numero;

	@Getter
	@Setter
	@Column
	@NotBlank(message = "Complemento : precisa ser preenchido.")
	private String complemento;

	@Getter
	@Setter
	@Column(nullable = false)
	@NotBlank(message = "Cep : precisa ser preenchido.")
	private String cep;

	@Getter
	@Setter
	@ManyToOne
	@JoinColumn(name = "pessoa_id", nullable = true)
	private Pessoa pessoa;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Endereco other = (Endereco) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/adailsilva/model/Funcionario.java
package com.adailsilva.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name="funcionario")
@PrimaryKeyJoinColumn(name="idPessoa")
public class Funcionario extends Pessoa implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date admissao;

	@Getter
	@Setter
	@Column(nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date demissao;

	

}

src/main/java/com/adailsilva/model/GrupoMesas.java
package com.adailsilva.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "grupo_mesas")
public class GrupoMesas {

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Getter
	@Setter
	@ManyToOne
	@JoinColumn(name = "mesa_id", nullable = false)
	private Mesa mesaSelecionada;

	@Getter
	@Setter
	@Column(nullable = false, name = "numero_mesas")
	private String numeroMesas;

	@Getter
	@Setter
	@Column(nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date dataInicio;

	@Getter
	@Setter
	@Column(nullable = true)
	@Temporal(TemporalType.TIMESTAMP)
	private Date dataFim;

}

src/main/java/com/adailsilva/model/ItemPedido.java
package com.adailsilva.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import lombok.Getter;
import lombok.Setter;


@Entity
@Table(name = "item_pedido")
public class ItemPedido implements Serializable {

	public enum StatusIP {
		ANDAMENTO, CANCELADO, RETIRADA, FINALIZADO
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Getter
	@Setter
	@Column(nullable = false)
	private Integer quantidade = 0;

	@Getter
	@Setter
	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	private Date data;

	@Getter
	@Setter
	@Column(nullable = false)
	private BigDecimal valorUnitario = BigDecimal.ZERO;

	@Getter
	@Setter
	@ManyToOne
	@JoinColumn(name = "produto_id", nullable = false)
	private Produto produto;
	
	@Getter
	@Setter
	@ManyToOne
	@JoinColumn(name = "funcionario_id", nullable = true)
	private Pessoa funcionario;

	
	@Getter
	@Setter
	@ManyToOne
	@JoinColumn(name = "pedido_id", nullable = false)
	private Pedido pedido;

	@Getter
	@Setter
	@Column(nullable = false)
	private Integer sequencia;

	@Getter
	@Setter
	@Column(nullable = false, name = "status_ip")
	@Enumerated(EnumType.STRING)
	private StatusIP statusIp;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ItemPedido other = (ItemPedido) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Transient
	public BigDecimal getValorTotal() {
		return this.getValorUnitario().multiply(new BigDecimal(this.getQuantidade()));
	}

	@Override
	public String toString() {
		return "ItemPedido [id=" + id + ", quantidade=" + quantidade + ", data=" + data + ", valorUnitario="
				+ valorUnitario + ", produto=" + produto + ", pedido=" + pedido + ", sequencia=" + sequencia
				+ ", statusIp=" + statusIp + "]";
	}

}

src/main/java/com/adailsilva/model/Menu.java
package com.adailsilva.model;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.constraints.NotBlank;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "menu")
public class Menu {

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Getter
	@Setter
	@Column(nullable = false, length = 20)
	@NotBlank(message = ": Descrição precisa ser preenchida !")
	private String descricao;

	@Getter
	@Setter
	@Column(nullable = false, length = 20)
	private String tipo;

	@Getter
	@Setter
	@ManyToOne
	private Menu menuPai;

	@Getter
	@Setter
	@OneToMany(mappedBy = "menuPai")
	private List<Menu> subMenus;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Menu other = (Menu) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/adailsilva/model/Meta.java
package com.adailsilva.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import com.adailsilva.model.Pedido.Status;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "meta")
public class Meta implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public enum StatusMeta {
		ANDAMENTO, FINALIZADO
	}

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Getter
	@Setter
	@OneToOne
	@JoinColumn(name = "restaurante_id", nullable = false)
	private Restaurante restaurante;

	@Getter
	@Setter
	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	@NotNull(message = "Data inicial precisa ser preenchida.")
	private Date dataInicial;

	@Getter
	@Setter
	@Column(nullable = false)
	@Temporal(TemporalType.TIMESTAMP)
	@NotNull(message = "Data final precisa ser preenchida.")
	private Date dataFinal;

	@Getter
	@Setter
	@Column(nullable = false)
	@NotNull(message = "Valor total :  precisa ser preenchido.")
	private BigDecimal valorTotal;

	@Getter
	@Setter
	@Column(nullable = true)
	private BigDecimal valorCorrente = BigDecimal.ZERO;

	@Getter
	@Setter
	@ManyToOne
	private Pessoa funcionario;

	@Getter
	@Setter
	@Column(nullable = false)
	@Enumerated(EnumType.STRING)
	private StatusMeta status;

	@Transient
	public Double getPorcentagem() {
		return ((100 * valorCorrente.doubleValue()) / valorTotal.doubleValue());
	}

}

src/main/java/com/adailsilva/model/Pagamento.java
package com.adailsilva.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "pagamento")
public class Pagamento implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	@Getter
	@Setter
	@Column(nullable = false)
	@OneToMany(mappedBy = "pagamento")
	private List<TipoPagamento> pagamento = new ArrayList<>();

	@Getter
	@Setter
	@OneToOne
	@JoinColumn(nullable = false)
	private Pedido pedido;

	@Getter
	@Setter
	@Column(nullable = false)
	private BigDecimal valor = BigDecimal.ZERO;

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Pagamento other = (Pagamento) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/com/adailsilva/model/adapter/ClienteAdapter.java
package com.adailsilva.model.adapter;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

public class ClienteAdapter {

	@Getter
	@Setter
	private Date data;
	@Getter
	@Setter
	private Long numeros;

	public ClienteAdapter(Date data, Long numeros) {
		this.data = data;
		this.numeros = numeros;
	}

}

src/main/webapp/404.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">

    <h:head>
        <f:facet name="first">
            <meta http-equiv="X-UA-Compatible" content="IE=edge" />
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
            <meta name="apple-mobile-web-app-capable" content="yes" />
        </f:facet>
        <title>PrimeFaces Ultima</title>
        <h:outputScript name="js/ripple.js" library="ultima-layout" />
    </h:head>

    <h:body styleClass="exception-body notfound-page">
    
        <div class="exception-type">
            <p:graphicImage name="images/404.svg" library="ultima-layout" />
        </div>
        
        <div class="card exception-panel">
            <i class="material-icons">&#xE001;</i>
            <h1>Page não encontrada</h1>
            <div class="exception-detail"></div>
            <p:button outcome="/dashboard" value="Home" styleClass="secondary"/>
        </div>
        
        <h:outputStylesheet name="css/ripple.css" library="ultima-layout" />
        <h:outputStylesheet name="css/layout-#{guestPreferences.theme}.css" library="ultima-layout" />
    </h:body>

</html>

src/main/webapp/empty.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">




	<ui:define name="content">
		<h:form id="frm">
			<div class="card">
				<div class="container-fluid">
					<h:inputText styleClass="moeda">
						<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
					</h:inputText>

				</div>
			</div>
		</h:form>
		
	</ui:define>



</ui:composition>

src/main/webapp/metas.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">




	<ui:define name="content">
		<h:form id="frm">
			<div class="card">
				<div class="container-fluid">
					<h3>Metas</h3>

					<p:toolbar>
						<f:facet name="left">
							<p:commandButton value="Nova" icon="ui-icon-document"
								action="#{metasBean.nova()}" update="frm" process="@this" />

							<p:commandButton action="#{metasBean.listar()}" update="frm"
								immediate="true" process="@form" value="Todas"
								icon="ui-icon-list" />


						</f:facet>



					</p:toolbar>

					<br />

					<p:messages id="message" closable="true" />
					<br />
					<h:panelGroup id="nova"
						rendered="#{metasBean.chooseOption == true}">

						<h4>Criação de meta</h4>

						<div class="row">
							<div class="col-md-2">
								<p:outputLabel value="Data  : " />
							</div>
							<div class="col-md-2">

								<h:panelGrid columns="3">
									<p:inputMask mask="99/99/9999" styleClass="larguraMax"
										value="#{metasBean.meta.dataInicial}">
										<f:convertDateTime pattern="dd/MM/yyyy"
											timeZone="America/Fortaleza" />
									</p:inputMask>
									<p:outputLabel value=" até "
										style="margin-left:3px;margin-right:3px;" />
									<p:inputMask mask="99/99/9999" styleClass="larguraMax"
										value="#{metasBean.meta.dataFinal}">
										<f:convertDateTime pattern="dd/MM/yyyy"
											timeZone="America/Fortaleza" />
									</p:inputMask>
								</h:panelGrid>
							</div>

						</div>

						<div class="row">
							<div class="col-md-2">
								<p:outputLabel value="Valor total  : " />
							</div>
							<div class="col-md-2">
								<p:inputText styleClass="larguraMax moeda"
									value="#{metasBean.meta.valorTotal}">
									<f:convertNumber maxFractionDigits="2" minFractionDigits="2" />
								</p:inputText>
							</div>

						</div>

						<div class="row" style="margin-bottom: 5px;">

							<div class="col-md-2">
								<p:outputLabel value="Funcionário :" />
							</div>
							<div class="col-md-2">
								<p:selectOneMenu styleClass="larguraMax" filter="true"
									value="#{metasBean.funcionarioSelecionado}">
									<f:selectItems itemLabel="#{c.nome} #{c.sobrenome} "
										itemValue="#{c}" value="#{metasBean.funcionarios}" var="c" />
									<f:selectItem noSelectionOption="true" itemLabel="Selecione" />
								</p:selectOneMenu>
							</div>
						</div>
						<div class="row" style="margin-bottom: 5px;">

							<div class="col-md-2">
								<p:commandButton value="Cadastrar" process="nova"
									update="nova message" action="#{metasBean.salvar}"
									styleClass="larguraMax green-btn" />
							</div>
						</div>

					</h:panelGroup>
					<h:panelGroup id="todas"
						rendered="#{metasBean.chooseOption == false}">
						<h4>Lista</h4>

						<p:dataTable value="#{metasBean.metas}" var="m" reflow="true">
							<p:column headerText="Data inicial">
								<p:outputLabel value="#{m.dataInicial}">
									<f:convertDateTime pattern="dd/MM/yyyy "
										timeZone="America/Fortaleza" />
								</p:outputLabel>
							</p:column>
							<p:column headerText="Data final">
								<p:outputLabel value="#{m.dataFinal}">
									<f:convertDateTime pattern="dd/MM/yyyy "
										timeZone="America/Fortaleza" />
								</p:outputLabel>
							</p:column>
							<p:column headerText="Valor total">
								<p:outputLabel value="R$ #{m.valorTotal}" />
							</p:column>
							<p:column headerText="Funcionário">
								<p:outputLabel
									value="#{m.funcionario == null ? 'N/A' : m.funcionario.nome }" />
							</p:column>
							<p:column headerText="Progresso">
								<p:progressBar value="#{m.porcentagem}" labelTemplate="{value}%"
									styleClass="larguraMax" displayOnly="true" />
							</p:column>

							<p:column headerText="Status">
								<p:commandButton styleClass="green-btn larguraMax"
									value="Finalizado" rendered="#{m.status == 'FINALIZADO'}" />
								<p:commandButton styleClass="amber-btn larguraMax"
									value="Andamento" rendered="#{m.status == 'ANDAMENTO'}" />
							</p:column>

						</p:dataTable>


					</h:panelGroup>


				</div>
			</div>
		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/minhasReservas.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" template="/WEB-INF/template.xhtml">




	<ui:define name="content">
		<h:form id="frm">
			<div class="card">
				<h4>Minhas reservas</h4>
				<div class="container-fluid">

					<p:dataTable value="#{minhasReservasBean.reservas}" var="r"
						emptyMessage="Nenhuma reserva encontrada">

						<p:column headerText="Data">
							<p:outputLabel value="#{r.data}">
								<f:convertDateTime pattern="dd/MM/yyyy hh:mm"
									timeZone="America/Fortaleza" />
							</p:outputLabel>
						</p:column>
						<p:column headerText="Ativo">
							<p:commandButton value="Inativo" styleClass="red-btn green-btn larguraMax"
								rendered="#{r.ativo == false}" />
							<p:commandButton value="Ativo"
								styleClass="green-btn larguraMax" rendered="#{r.ativo == true}" />
						</p:column>
						<p:column headerText="Mesa">
							<p:outputLabel value="#{r.mesa.numeroMesa}" />
						</p:column>

					</p:dataTable>


				</div>
			</div>
		</h:form>
	</ui:define>

</ui:composition>